Improve division filtering
jessecoleman/nsf-viz pull request #37
Opened 2022-01-29 22:22 UTC by jessecoleman

- filtering now correctly filters both top-level and nested divisions, expanding categories with matches automatically
- use react-flip-toolkit to create transitions during filtering

2022-02-04 21:38 UTC, h1-the-swan requested changes

2022-02-04 21:38 UTC, h1-the-swan commented on frontend/src/app/nav/Drawer.tsx
> +import DirectoryTree from 'app/divisions/DirectoryTree';
Module not found error. Did you forget to commit the `DirectoryTree` file?

2022-02-05 00:48 UTC, h1-the-swan requested changes

2022-02-05 00:48 UTC, h1-the-swan commented on frontend/src/app/divisions/DirectoryTree.tsx
> +import { stableSort } from 'app/sort';
This file (`app/sort`) doesn't exist. But also, `stableSort` isn't used. Can we remove this line?

2022-02-05 00:49 UTC, jessecoleman commented on frontend/src/app/divisions/DirectoryTree.tsx
> +import { stableSort } from 'app/sort';
Sorry about that, yeah just delete the import.

2022-02-05 00:55 UTC, h1-the-swan approved these changes

2022-02-05 00:55 UTC, merged