Term lemmas
jessecoleman/nsf-viz pull request #42
Opened 2022-03-06 23:16 UTC by jessecoleman

- show term lemmas in suggestions dropdown
- show recommended keywords in abstract dialog
- suggest topics to search for if no terms in input field
- overhaul input field styling to improve animations/transitions
- new steps in training pipeline to support new NLP features

2022-03-28 19:08 UTC, h1-the-swan requested changes

2022-03-28 19:08 UTC, h1-the-swan commented on backend/app.py
> +import analyze
backend startup fails for me: `ModuleNotFoundError: No module named 'analyze'`

2022-04-06 14:34 UTC, jessecoleman commented on backend/app.py
> +import analyze
should be fixed now

2022-04-08 23:42 UTC, h1-the-swan requested changes
Aside from the assets file that needs to be committed, it's looking good. Is there a way to turn off the new features to present the version from before?

2022-04-25 21:44 UTC, h1-the-swan approved these changes
Looking good! I removed the `nltk` dependency because it looks like we're not using it anymore.

2022-04-25 21:56 UTC, merged